export const STYLE_ATTRIBUTES = [
  "backgroundColor",
  "color",
  "direction",
  "display",
  "displayAlign",
  "extent",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontWeight",
  "lineHeight",
  "opacity",
  "origin",
  "overflow",
  "padding",
  "textAlign",
  "textDecoration",
  "unicodeBidi",
  "visibility",
  "writingMode",

  // Not managed anywhere for now
  // "showBackground",
  // "textOutline",
  // "wrapOption",
  // "zIndex",
];
