# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"

branches:
  only:
    - master
    - /^release\/.*$/

# Install scripts. (runs after repo cloning)
install:
  # - choco install firefox
  # - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run check:appveyor

# Don't actually build.
build: off
