/**
 * Merge headers generated by the RxPlayer with custom request headers.
 * Custom headers take precedence, independently of their casing.
 * @param {Object|undefined} baseHeaders
 * @param {Object|undefined} newHeaders
 * @returns {Object|undefined}
 */
export default function mergeRequestHeaders(
  baseHeaders: Record<string, string> | undefined,
  newHeaders: Record<string, string> | undefined,
): Record<string, string> | undefined {
  if (baseHeaders === undefined) {
    return newHeaders === undefined ? undefined : { ...newHeaders };
  }
  if (newHeaders === undefined) {
    return baseHeaders;
  }

  const headers = { ...baseHeaders };
  for (const headerName of Object.keys(newHeaders)) {
    const lowerCasedHeaderName = headerName.toLowerCase();
    for (const currentHeaderName of Object.keys(headers)) {
      if (currentHeaderName.toLowerCase() === lowerCasedHeaderName) {
        delete headers[currentHeaderName];
      }
    }
    headers[headerName] = newHeaders[headerName];
  }
  return headers;
}
