#!/bin/bash

# Generate builds
# ===============
#
# This script allows to automatically generate a modular build with all its
# associated files and directories.
#
# To use it:
#   1. Be sure that you're on the branch you want to build.
#   2. Call this script and wait...
#   3. That's it!

set -e

echo "cleaning previous builds..."
./scripts/clean-up_builds

echo "bundling raw modular version..."
npm run prepare:modular
rm dist/_esm5.raw/exports.js

echo "processing raw modular build..."
cp -r dist/_esm5.raw/ dist/_esm5.processed

# TODO So ugly right now. We should find a way to transform the JS in a cleaner
# way
files="$(find dist/_esm5.processed -type f -iname '*.js')"

# macOS comes with the BSD version of some command line tools, which are
# slightly different from the Linux version. The -i argument on sed
# doesn't work with a zero-length extension. Thus, we declare an extension,
# and then delete back-up unwanted files.
if [[ "$OSTYPE" == "darwin"* ]]; then
  for f in "$files"; do
    sed -i.DELETE -E "s/[[:<:]]__DEV__[[:>:]]/false/g" $f

    sed -i.DELETE -E "s/[[:<:]]__LOGGER_LEVEL__[[:>:]]/\"NONE\"/g" $f

    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.EME[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.SMOOTH[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.DASH[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.LOCAL_MANIFEST[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.DIRECTFILE[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.METAPLAYLIST[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.HTML_SAMI[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.HTML_SRT[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.HTML_TTML[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.HTML_VTT[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.NATIVE_SAMI[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.NATIVE_SRT[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.NATIVE_TTML[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.NATIVE_VTT[[:>:]]/false/g" $f
    sed -i.DELETE -E "s/[[:<:]]__FEATURES__\.BIF_PARSER[[:>:]]/false/g" $f

    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.EME_MANAGER[[:>:]]/\"..\/core\/eme\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.IMAGE_BUFFER[[:>:]]/\"..\/custom_source_buffers\/image\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.BIF_PARSER[[:>:]]/\"..\/parsers\/images\/bif.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.SMOOTH[[:>:]]/\"..\/transports\/smooth\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.DASH[[:>:]]/\"..\/transports\/dash\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.LOCAL_MANIFEST[[:<:]]/\"..\/transports\/local\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.METAPLAYLIST[[:>:]]/\"..\/transports\/metaplaylist\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.NATIVE_TEXT_BUFFER[[:>:]]/\"..\/custom_source_buffers\/text\/native\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.NATIVE_VTT[[:>:]]/\"..\/parsers\/texttracks\/webvtt\/native.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.NATIVE_SRT[[:>:]]/\"..\/parsers\/texttracks\/srt\/native.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.NATIVE_TTML[[:>:]]/\"..\/parsers\/texttracks\/ttml\/native\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.NATIVE_SAMI[[:>:]]/\"..\/parsers\/texttracks\/sami\/native.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.HTML_TEXT_BUFFER[[:>:]]/\"..\/custom_source_buffers\/text\/html\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.HTML_VTT[[:>:]]/\"..\/parsers\/texttracks\/webvtt\/html\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.HTML_SRT[[:>:]]/\"..\/parsers\/texttracks\/srt\/html.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.HTML_TTML[[:>:]]/\"..\/parsers\/texttracks\/ttml\/html\/index.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.HTML_SAMI[[:>:]]/\"..\/parsers\/texttracks\/sami\/html.js\"/g" $f
    sed -i.DELETE -E "s/[[:<:]]__RELATIVE_PATH__\.DIRECTFILE[[:>:]]/\"..\/core\/init\/directfile.js\"/g" $f
  done

  find dist/_esm5.processed -type f -name "*.DELETE" -delete
else
  for f in "$files"; do
    sed -i -E "s/\b__DEV__\b/false/g" $f

    sed -i -E "s/\b__LOGGER_LEVEL__\b/\"NONE\"/g" $f

    sed -i -E "s/\b__FEATURES__\.EME\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.SMOOTH\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.DASH\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.LOCAL_MANIFEST\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.METAPLAYLIST\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.DIRECTFILE\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.HTML_SAMI\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.HTML_SRT\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.HTML_TTML\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.HTML_VTT\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.NATIVE_SAMI\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.NATIVE_SRT\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.NATIVE_TTML\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.NATIVE_VTT\b/false/g" $f
    sed -i -E "s/\b__FEATURES__\.BIF_PARSER\b/false/g" $f

    sed -i -E "s/\b__RELATIVE_PATH__\.EME_MANAGER\b/\"..\/core\/eme\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.IMAGE_BUFFER\b/\"..\/custom_source_buffers\/image\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.BIF_PARSER\b/\"..\/parsers\/images\/bif.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.SMOOTH\b/\"..\/transports\/smooth\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.DASH\b/\"..\/transports\/dash\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.LOCAL_MANIFEST\b/\"..\/transports\/local\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.METAPLAYLIST\b/\"..\/transports\/dash\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.NATIVE_TEXT_BUFFER\b/\"..\/custom_source_buffers\/text\/native\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.NATIVE_VTT\b/\"..\/parsers\/texttracks\/webvtt\/native.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.NATIVE_SRT\b/\"..\/parsers\/texttracks\/srt\/native.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.NATIVE_TTML\b/\"..\/parsers\/texttracks\/ttml\/native\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.NATIVE_SAMI\b/\"..\/parsers\/texttracks\/sami\/native.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.HTML_TEXT_BUFFER\b/\"..\/custom_source_buffers\/text\/html\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.HTML_VTT\b/\"..\/parsers\/texttracks\/webvtt\/html\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.HTML_SRT\b/\"..\/parsers\/texttracks\/srt\/html.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.HTML_TTML\b/\"..\/parsers\/texttracks\/ttml\/html\/index.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.HTML_SAMI\b/\"..\/parsers\/texttracks\/sami\/html.js\"/g" $f
    sed -i -E "s/\b__RELATIVE_PATH__\.DIRECTFILE\b/\"..\/core\/init\/directfile.js\"/g" $f
  done
fi

echo "processed modular build succesfully created!"

echo "creating minimal build..."
rm -rf minimal
mkdir minimal
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import MinimalPlayer from \"../dist/_esm5.processed/minimal.js\";
export default MinimalPlayer;" > minimal/index.js
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import MinimalPlayer from \"../dist/_esm5.processed/minimal\";
export default MinimalPlayer;" > minimal/index.d.ts

echo "creating features build..."
rm -rf features
mkdir features
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../dist/_esm5.processed/features/list/index.js\";" > features/index.js
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../dist/_esm5.processed/features/list/index\";" > features/index.d.ts

echo "creating experimental build..."
rm -rf experimental
mkdir -p experimental/tools
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../../dist/_esm5.processed/experimental/tools/index.js\";" > experimental/tools/index.js
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../../dist/_esm5.processed/experimental/tools/index\";" > experimental/tools/index.d.ts

mkdir -p experimental/features
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../../dist/_esm5.processed/experimental/features/index.js\";" > experimental/features/index.js
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../../dist/_esm5.processed/experimental/features/index\";" > experimental/features/index.d.ts

echo "creating types build..."
rm -rf types
mkdir types
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */" > types/index.js
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export * from \"../dist/_esm5.processed/public_types\";" > types/index.d.ts

echo "creating types for legacy code bases..."
rm -f dist/rx-player.d.ts rx-player.min.d.ts
echo "/**
 * Copyright 2015 CANAL+ Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import RxPlayer from \"./_esm5.processed/index\";
export default RxPlayer;" | tee dist/rx-player.d.ts dist/rx-player.min.d.ts > /dev/null

echo "done"
