#!/bin/bash

# Generate certificate
# ====================
#
# This script allows to create a self-signed ssl certificate easily.
# One of the goal here, is to be able to easily test HTTPS pages.

openssl req \
  -x509 \
  -out localhost.crt \
  -keyout localhost.key \
  -newkey rsa:2048 \
  -nodes \
  -sha256 \
  -subj "/C=FR/L=Paris/O=CANAL+"
