#!/bin/bash

# make-dev-releases
# =================
#
# This script produces pre-releases on top of the current branch for the
# `dev` and `canal` versions (as per their npm tags).
#
# To use it:
#
#   1. Be sure that you're on the branch corresponding to the pre-release you
#      want to publish, at the repository's root directory.
#
#   2. Call this script followed with the corresponding version number it would
#      have as an official release in the `MAJOR.MINOR.PATCH` format (e.g.
#      `./update-version 4.1.3`). Special suffix corresponding to the date and
#      tag will be added automatically by this script.
#
#   3. When the script ask you to confirm, check that the preceding commands did
#      not output any issue and if it didn't you can confirm.
#
#   4. That's it!

set -e

if [ $# -eq 0 ]; then
 echo "no version in argument"
 exit 1
fi

current_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
version=$1
date=$(date "+%Y%m%d")
dev_branch="release/v${version}-dev.${date}00"
canal_branch="release/v${version}-canal.${date}00"

git checkout -b ${dev_branch}
./scripts/update-version $1-dev.${date}00
git add --all
git commit -m "update version"
while true; do
  read -n1 -p "Do you wish to push and publish the dev build? [y/n] " yn
  echo ""
  case $yn in
    [Yy]* ) break;;
    [Nn]* ) exit;;
    * ) echo "Please answer y or n.";;
  esac
done
git push origin ${dev_branch}
npm publish --tag dev

git checkout $current_branch

git checkout -b ${canal_branch}
git apply ./scripts/canal-release.patch
./scripts/update-version $1-canal.${date}00
git add --all
git commit -m "update version"
git push origin ${canal_branch}
while true; do
  read -n1 -p "Do you wish to push and publish the canal build? [y/n] " yn
  echo ""
  case $yn in
    [Yy]* ) break;;
    [Nn]* ) exit;;
    * ) echo "Please answer y or n.";;
  esac
done
npm publish --tag canal
