#!/bin/bash

# Report build sizes
# ==================
#
# This script allows to report the sizes of multiple minified rx-player bundles,
# each either with a different set of features.
#
# To use it:
#
#   1. Be sure you're on the branch on which you want to check the build size on
#
#   2. Call this script and wait some time
#
#   3. Every build size will be written in a `sizes` files, under the format:
#      `BUILD_DESCRIPTION: SIZE_OF_THE_BUILD_IN_BYTES`

npm run build:min
echo -n "REGULAR: " > sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_DASH=false npm run build:min
echo -n "w/o DASH: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_SMOOTH=false npm run build:min
echo -n "w/o SMOOTH: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_DIRECTFILE=false npm run build:min
echo -n "w/o DIRECTFILE: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_NATIVE_TTML=false npm run build:min
echo -n "w/o NATIVE_TTML: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_NATIVE_SAMI=false npm run build:min
echo -n "w/o NATIVE_SAMI: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_NATIVE_VTT=false npm run build:min
echo -n "w/o NATIVE_VTT: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_NATIVE_SRT=false npm run build:min
echo -n "w/o NATIVE_SRT: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_HTML_TTML=false npm run build:min
echo -n "w/o HTML_TTML: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_HTML_SAMI=false npm run build:min
echo -n "w/o HTML_SAMI: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_HTML_VTT=false npm run build:min
echo -n "w/o HTML_VTT: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_HTML_SRT=false npm run build:min
echo -n "w/o HTML_SRT: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_EME=false npm run build:min
echo -n "w/o EME: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_BAREBONE=true npm run build:min
echo -n "BAREBONE: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_NATIVE_TTML=false RXP_NATIVE_SAMI=false RXP_NATIVE_VTT=false RXP_NATIVE_SRT=false npm run build:min
echo -n "w/o NATIVE TEXT TRACKS: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_HTML_TTML=false RXP_HTML_SAMI=false RXP_HTML_VTT=false RXP_HTML_SRT=false npm run build:min
echo -n "w/o HTML TEXT TRACKS: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_METAPLAYLIST=true npm run build:min
echo -n "with METAPLAYLIST: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes

RXP_LOCAL_MANIFEST=true npm run build:min
echo -n "with LOCAL_MANIFEST: " >> sizes
stat -c %s dist/rx-player.min.js >> sizes
