#!/bin/bash
set -e

version=$1

sed -i.bak -e "s/``v[0-9]\+\.[0-9]\+\.[0-9]\+\(-\w\+[0-9]\)\?``/``v${version}``/g" README.md && rm README.md.bak;
sed -i.bak -e "s/\/\\*PLAYER_VERSION\\*\/\"\(.*\)\";/\/*PLAYER_VERSION*\/\"${version}\";/g" src/core/api/index.ts && rm src/core/api/index.ts.bak
sed -i.bak -e "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\(-\w\+[0-9]\)\?\"/\"version\": \"${version}\"/g" package.json && rm package.json.bak
sed -i.bak -e "s/sonar\.projectVersion= *[0-9]\+\.[0-9]\+\.[0-9]\+/sonar.projectVersion=${version}/g" sonar-project.properties && rm sonar-project.properties.bak
echo $version > VERSION

npm install
npm run build
npm run build:min
./scripts/generate_minimal_build
