#!/bin/bash

################################################################################
# This file allows to automatically update the full demo on the gh-pages branch.
#
# To use it:
#
#   1. Go to a clean master branch
#
#   2. Make sure the rx-player you want to use is bundled as
#      dist/rx-player.min.js
#
#   3. Update the full demo files (in demo/full) as you want
#
#   4. Call this script.
#      Some user interactions will be needed to avoid doing unwanted commits.
#
#   5. That's it!
#      A commit should have been pushed to master and gh-pages.
#
################################################################################

set -e

current_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if ! [ $current_branch == "master" ]; then
  echo $current_branch
  echo "ERROR: The current branch should be master"
  exit 1;
fi

tmpFontsDir=$(mktemp -d)
tmpAssetsDir=$(mktemp -d)
tmpStylesDir=$(mktemp -d)
tmpDemoFile=$(mktemp)
tmpRxPlayerFile=$(mktemp)

# Generate demo
npm run demo:min
cp -r demo/full/fonts $tmpFontsDir -v
cp -r demo/full/assets $tmpAssetsDir -v
cp -r demo/full/styles $tmpStylesDir -v
cp demo/full/bundle.js $tmpDemoFile -v
cp dist/rx-player.min.js $tmpRxPlayerFile -v

if [ -n "$(git status --porcelain demo/full)" ]; then
  echo "-- Current Status on master: --"
  echo ""
  git status demo/full

  while : ; do
    echo ""
    echo "We will push the demo to master."
    REPLY=""
    read -p "do you want to continue [y/d/s/a/c/t/h] (h for help) ? " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Hh](elp)?$ ]]; then
      echo ""
      echo ""
      echo "+- help -------------------------------------------------+"
      echo "| y: commit and continue                                 |"
      echo "| d: see diff                                            |"
      echo "| s: see status                                          |"
      echo "| a: abort script from here                              |"
      echo "| c: checkout from this commit and go to the next one    |"
      echo "| t: stash this commit and go to the next one            |"
      echo "| h: see this help                                       |"
      echo "+--------------------------------------------------------+"
    elif [[ $REPLY =~ ^[Aa]bort?$ ]]; then
      echo "exiting"
      rm -r $tmpFontsDir
      rm -r $tmpAssetsDir
      rm -r $tmpStylesDir
      rm $tmpRxPlayerFile $tmpDemoFile
      exit 0
    elif [[ $REPLY =~ ^[Yy](es)?$ ]]; then
      git add demo/full
      git commit -m "update demo" -S
      git push origin master
      break
    elif [[ $REPLY =~ ^[Cc](heckout)?$ ]]; then
      git checkout demo/full
      break
    elif [[ $REPLY =~ ^[Ss](tatus)?$ ]]; then
      git status demo/full
    elif [[ $REPLY =~ ^([Tt]|([Ss]tash))?$ ]]; then
      git stash -u push demo/full
    elif [[ $REPLY =~ ^[Dd](iff)?$ ]]; then
      git diff demo/full || true # ignore when return 1
    fi
  done
else
  echo "nothing to do on the master branch"
fi

# update gh-pages
git checkout gh-pages
git pull origin gh-pages
rm -rf styles
mv $tmpFontsDir
mv $tmpAssetsDir
mv $tmpStylesDir/styles .
mv $tmpRxPlayerFile rx-player.js
mv $tmpDemoFile bundle.js

if [ -n "$(git status --porcelain demo/full)" ]; then
  echo "-- Current Status on gh-pages: --"
  echo ""
  git status rx-player.js bundle.js styles fonts assets

  while : ; do
    echo ""
    echo "We will push the demo to gh-pages."
    REPLY=""
    read -p "do you want to continue [y/d/s/a/c/t/h] (h for help) ? " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Hh](elp)?$ ]]; then
      echo ""
      echo ""
      echo "+- help -------------------------------------------------+"
      echo "| y: commit and continue                                 |"
      echo "| d: see diff                                            |"
      echo "| s: see status                                          |"
      echo "| a: abort script from here                              |"
      echo "| c: checkout from this commit and go to the next one    |"
      echo "| t: stash this commit and go to the next one            |"
      echo "| h: see this help                                       |"
      echo "+--------------------------------------------------------+"
    elif [[ $REPLY =~ ^[Yy](es)?$ ]]; then
      git add rx-player.js bundle.js styles fonts assets
      git commit -m "update demo" -S
      git push origin gh-pages
      break
    elif [[ $REPLY =~ ^[Dd](iff)?$ ]]; then
      git diff rx-player.js bundle.js styles fonts assets || true # ignore when return 1
    elif [[ $REPLY =~ ^[Ss](tatus)?$ ]]; then
      git status rx-player.js bundle.js styles fonts assets
    elif [[ $REPLY =~ ^[Aa](bort)?$ ]]; then
      echo "exiting"
      exit 0
    elif [[ $REPLY =~ ^[Cc](heckout)?$ ]]; then
      git checkout rx-player.js bundle.js styles fonts assets
    elif [[ $REPLY =~ ^([Tt]|([Ss]tash))?$ ]]; then
      git stash -u push rx-player.js bundle.js styles fonts assets
      break
    fi
  done
else
  echo "nothing to do on the gh-pages branch"
fi

git checkout master
