name: RxPlayer Windows

on: [push]

jobs:

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Bash Script
        shell: bash
        run: |
          npm run ci
          npm run build
          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
