name: RxPlayer npm publishing

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # v1.0.0, v2.3.4 … nothing else

jobs:
  publish_official:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # required for npm provenance

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - run: |
          npm ci
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
