name: RxPlayer Script Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - scripts/**

jobs:
  scripts_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install JS dependencies
        run: npm ci
      - name: Typecheck files in the scripts directory
        run: npm run types:scripts
      - name: Lint files in the scripts directory
        run: npm run lint:scripts
